### ISSUE TITLE
More sorting options?

### ISSUE THREAD

**Issue by krab** [poeapp/poeapp#1]
For example missing properties.Buyout. Time when items was listed. Str, dex, int and level requirements.

Clicking on buyouts, date and requirements do nothing atm.

**Comment by poeapp** [comment]
Alright, sort by buyout has been a very popular request.  That has now been implemented.  Please hold shift and click refresh to pull the latest.

**Comment by krab** [comment]
So this is how app works, we need fully refresh page after code/api mechanics changes? Why not check something like version stored in cookies or somewhere and force refresh?

**Comment by poeapp** [comment]
It should pick it up but it requires two refreshes.  Shift+refresh will pull new changes in on the first refresh.

**Comment by poeapp** [comment]
Added sort by ilvl and last updated.
