### ISSUE TITLE
Ads are not displayed when adblocker is disabled.

### ISSUE THREAD

**Issue by jannisg** [poeapp/poeapp#102]
### Did you clear your browser cache before trying to reproduce?
- [x] Yes

### App Version

`7599d7359664954bee4e4b09e9d75b83b2542174`

### Description
The adblocker message is shown instead of an ad even though the adblocker has the `poeapp.com` domain whitelisted to enable the site to show its ads.

> Your support allows me to continue adding new features and pay for my infrastructure costs.
Please disable your adblocker.

![adblock-no-ad](https://user-images.githubusercontent.com/109211/29236221-c7d084a6-7f5b-11e7-8514-6144c538b9a7.JPG)

### Expected outcome
Ads should be shown instead of the message since the Adblocker is not running.

### Actual outcome
Ads are not shown and the "please disable your adblocker" message is shown instead.

### Steps to reproduce
Appears on all search pages, no specific steps required though I'm happy to provide more details etc if required.

### Browsers Affected

- [x] Chrome (`Version 60.0.3112.90 (Official Build) (64-bit)`) (Windows 10)

**Comment by poeapp** [comment]
@jannisg Can you please do a test for me with that extension entirely disabled and post your results?

**Comment by jannisg** [comment]
@poeapp Sorry about the delay, just disabled the extension in Chrome and the banner disappears now and the ad loads in as it should.

I'm personally not sure how but surely there must be a way to detect if the extension is actively blocking your site vs running but allowing ads to be loaded?

I could look into this for you if that would help.

**Comment by poeapp** [comment]
Adblock and Adblock Plus do this thing on my site where even though they're disabled, they still block ads.  You can see this with the little number 1 in the bottom right of the Adblock icon.  I know it can be hard to switch adblockers, but I would really recommend using uBlock Origin if possible.

**Comment by jannisg** [comment]
Switched to uBlock Origin 👍
