### ISSUE TITLE
Searching for Pseudo Max Life

### ISSUE THREAD

**Issue by gabrielsubzero** [poeapp/poeapp#107]
I think that it would help alot if it was possible to search for maximum life with the life given by strength if possible. It would make hunting for items with life much more easy.

**Comment by gabrielsubzero** [comment]
I am sorry,that is already possible,iguess it is just under total instead of regular life. Sorry for bothering you.

**Comment by poeapp** [comment]
This exists today as `[total] +# to maximum Life`
