### ISSUE TITLE
[BUG] Wrong sockets alignment

### ISSUE THREAD

**Issue by dein0s** [poeapp/poeapp#111]
### Did you clear your browser cache before trying to reproduce?
- [x] Yes

### App Version
b34641b0551091e603d0544015cd710df5852d60

### Description
Wrong sockets alignment for the 1x3 items.

### Expected outcome
All sockets must be aligned identically.

### Actual outcome
For 1x3 items (wands, daggers, swords) 3-d socket shifted to the left side relatively to other sockets.
![sockets_chrome](http://i.imgur.com/VELXZeh.png)

### Steps to reproduce
1. Search for any 1x3 item (sword, dagger, wand) with 3 sockets
Example: https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4QALMaAEwGMB7aFAAgunlgDs8VoQAaEJwBmdDBDoBrFB1gAvFFQxDEWLADkwAWyKkAMrCHoADnDxMAInCEQA7nTpUmAdTAcq-EGjo0pETF58UCABhOkQOCBIAbRAAZg8QAF0AXyA

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome
- [x] [Vivaldi](https://vivaldi.com)

**Comment by poeapp** [comment]
This has been bothering me as well 👍 
[Fixed in version](http://imgur.com/a/KGOeq) `89a30d20aa80d3d5b1ebdad0bbabd8cd5e87a089 `
