### ISSUE TITLE
Search Options (Item age/one result per acc)

### ISSUE THREAD

**Issue by Eruyome** [poeapp/poeapp#113]
Additional search options:
- Item Age (in minutes) [min/max]
- Limit results to one per account [true/false]

Also, having median/average statistics on top of every search results page would be nice.

**Comment by poeapp** [comment]
Item Age is now resolved via https://twitter.com/subtract/status/1000160831034744832

If you would still like to see the other items addressed, could you please open separate tickets for them?  Thanks 👍
