### ISSUE TITLE
Contributions to the site?

### ISSUE THREAD

**Issue by jannisg** [poeapp/poeapp#114]
Hey,

Just wanted to check if contributions to the app would be welcomed and if so how I would go about forking the source and implementing some of the features from the Github Issues tracker since the master branch doesn't seem to have any of the code?

**Comment by poeapp** [comment]
Hey @jannisg,

Currently, I'm not accepting contributions, but I appreciate the interest.  Github is used solely for an explanation of how to build search URLs for poeapp and track issues/feature requests.

Thanks
