### ISSUE TITLE
Cold, Fire and Lightning Resistance in the Defense section could be in game order (Fire, Cold, Lightning)

### ISSUE THREAD

**Issue by Strackeror** [poeapp/poeapp#115]
A couple humble suggestions
- Cold, Fire and Lightning Resistance in the Defense section could be in game order (Fire, Cold, Lightning), I tripped up multiple searches because of this...

- When I search for items in a price range, 90% of the time I don't want to see unpriced items. Is it possible to automatically not search for unpriced while doing a search for a price range ?

**Comment by poeapp** [comment]
> When I search for items in a price range, 90% of the time I don't want to see unpriced items. Is it possible to automatically not search for unpriced while doing a search for a price range ?

There are two ways to accomplish this currently.  Set `Has Buyout` to `Yes` or set a minimum buyout (you should be able to set this to 0).

**Comment by poeapp** [comment]
Cold/Fire have been swapped in version `e63bc8fe9899a545b5feb5be0454b90f65b7a66b`
