### ISSUE TITLE
item-import.ahk URL doesn't work for Chrome

### ISSUE THREAD

**Issue by dellistic** [poeapp/poeapp#121]
### Did you clear your browser cache before trying to reproduce?
- [x] Yes. Even reinstalled a fresh stock portable Chrome.

### Did you disable all browser extensions before trying to reproduce?
- [x] Yes. Stock, fresh install.

### App Version

Current version is a60b5a1a86867531542460a4fbc9631ea1ecf524

### Description

I debugged the script and managed to extract the actual URI encoded url to debug why the search item mods are not reflected.
It works in Firefox, surprisingly. But not in chrome.

### Expected outcome

Item loads in browser with mods filled in.

### Actual outcome

Items loads in browser with only the name and type.

### Steps to reproduce

1. Use this URL encoded by item-import.ahk in Chrome.
URL used:
`https://poeapp.com/item-import/Rarity%3A%20Unique%0D%0AAbberath%27s%20Horn%0D%0AGoat%27s%20Horn%0D%0A%2D%2D%2D%2D%2D%2D%2D%2D%0D%0AWand%0D%0APhysical%20Damage%3A%207%2D13%0D%0ACritical%20Strike%20Chance%3A%207%2E00%25%0D%0AAttacks%20per%20Second%3A%201%2E20%0D%0A%2D%2D%2D%2D%2D%2D%2D%2D%0D%0ARequirements%3A%0D%0ALevel%3A%206%0D%0AInt%3A%2029%0D%0A%2D%2D%2D%2D%2D%2D%2D%2D%0D%0ASockets%3A%20B%2DB%20B%20%0D%0A%2D%2D%2D%2D%2D%2D%2D%2D%0D%0AItem%20Level%3A%2075%0D%0A%2D%2D%2D%2D%2D%2D%2D%2D%0D%0A11%25%20increased%20Spell%20Damage%0D%0A%2D%2D%2D%2D%2D%2D%2D%2D%0D%0A23%25%20increased%20Fire%20Damage%0D%0AAdds%204%20to%2010%20Fire%20Damage%20to%20Spells%0D%0A49%25%20increased%20Global%20Critical%20Strike%20Chance%0D%0A%2B10%20Life%20gained%20on%20Killing%20Ignited%20Enemies%0D%0A25%25%20reduced%20Ignite%20Duration%20on%20Enemies%0D%0A%2D%2D%2D%2D%2D%2D%2D%2D%0D%0AThe%20Goat%20King%20drank%20the%20smoke%20and%20ate%20the%20flames%0D%0Aas%20his%20ruin%20spread%20across%20the%20land%2E%0D%0A
`

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by dellistic** [comment]
Okay, really weird that the URL paste works now in Chrome...

Anyway the main issue I had was when specifying a browser to use I need to double quote the URL.
`;Run, https://poeapp.com/item-import/%itemContents%
;Run, firefox.exe "https://poeapp.com/item-import/%itemContents%"
Run, GoogleChromePortable.exe "https://poeapp.com/item-import/%itemContents%"`

**Comment by poeapp** [comment]
Is this only inconsistent in Chrome or also Safari/Opera?

**Comment by dellistic** [comment]
I only have Vivaldi | 1.12.955.36 (Stable channel) (32-bit) which also uses Blink engine, I get 10 out of 10 trying that URL 10 times. Back to back.

Using stock portable Chrome [Version 61.0.3163.100 (Official Build) (32-bit)] (no extension, no nothing, fresh install) I get 3 out of 10 working.
Basically very high failure to load the mods rate. Same for my normal Chrome.

Hope that helps in debugging.

**Comment by poeapp** [comment]
I tested in Chrome 60.0.3112.113 and Opera 46.0.2597.57 and was able to load the mods 100%.  Would you mind taking a few minutes to create a gfycat.com of what you're seeing, including the steps involved please?

**Comment by poeapp** [comment]
To expand on this, do you get any errors in the developer console when loading that URL?

**Comment by dellistic** [comment]
I'm testing using the URL in the original bug report. To have consistent test case.

https://gfycat.com/gifs/detail/jealousellipticalasianporcupine
(Got compressed to hell, dunno how to use gfycat as mp4, though I've seen reddit posts of very high quality...)
Alternatively: https://ufile.io/fqjm1 (It's only 1.2mb, will be deleted by the host in 30days)

Notice the mods part is totally empty. It's filled properly in Firefox and Vivaldi.

**Comment by dellistic** [comment]
As an additional data point, I found an older version of portable chrome lying in my hdd (Chrome 51), it goes 10/10 working properly.

I think those stuffs in the console I showed in the video above means something..

**Comment by poeapp** [comment]
Thanks for this.  I will look into it.

**Comment by poeapp** [comment]
Please confirm whether or not this is working in version `2017-11-23T04:01:47.751Z`.
