### ISSUE TITLE
Add compound filters (count effect on skill + weapon type + 2h/dual-wield, etc.)

### ISSUE THREAD

**Issue by Cypher121** [poeapp/poeapp#126]
An ability to filter items by how they affect specific setups is extremely useful, immeasurably so when buying jewels. For example, finding a jewel that adds 30% damage to Glacial Cascade Mines involves 5 mods: damage, spell damage, mine damage, cold damage and physical damage (phys to cold conversion). Any combination of 2 to 4 of those can provide a 30% boost, making searching all options virtually impossible.

One option on how it could work is:

1. Separate menu for filters, similar to current Mods

2. Drop-down selection of the skill used

3. Option to select either dual-wielding or two-handed weapon: each provides options to select weapon types (2 and 1 respectively, as well as bow/quiver) as well as a checkbox near to select whether that weapon is calculated for attack damage (e.g. Blade Flurry users would check both if using 2 claws or only main if using a stat stick that cannot use Blade Flurry)

4. Checkboxes for skill type conversions: traps, mines, totems.

5. Checkboxes for damage conversions (e.g. phys to cold) to allow searching for matching damage types.

6. Finally a list of properties to search for: this would work exactly like mod list and allow to select properties such as +% damage to skill, +% attack speed to skill, etc.

While this might involve some calculations of damage effects on the skill and may not be as easy to index by, I believe the end result will be a massive time and currency saver even if not 100% accurate.

**Comment by poeapp** [comment]
Can you please add some use cases that can help better demonstrate?  Just trying to gain a better understanding.

**Comment by Cypher121** [comment]
As I said, main use case I had in mind was searching for jewels. For instance, I want a jewel that gives at least 30% increased damage to my sword + stat-stick Blade Flurry. I would create a filter that specifies I dual-wield a sword + mace which does not affect damage and use Blade Flurry, and that I am looking for a +30% increased damage on that. 

This would match, for instance, jewels with +damage, +area damage, +phys damage, +dual wield damage, +sword damage and probably something else I forgot.

This is currently achievable by searching for a sum of every single of those affixes, but it is easy to forget one (so a better GUI would be a massive help) and does not allow searching for other mods as well (e.g. 6% life + 30% total damage, as far as I know, is not searchable)

**Comment by poeapp** [comment]
You could just create Presets for the searches that you care about.  It also sounds like you could just use the `sum` or `count` mod types in these instances, adding the fields that you care about.  Adding additional complexity to the indexer to support this inevitably makes the indexer more difficult to maintain for mods that could possibly change (in regards to how they calculate the damage) at GGG's discretion.

Here's an [example search using count](https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4QALMaAEwGMB7aFAAgunlgDs8VoQAacFDhJUmWKgC2AFQCeAByKkAUigDuKLPxAS6VNCQDaoHXpKgUADzlZYNcRgDEAUiacajMGhRUmAQQ9MACJgEviKBhyIWFh8kdEAugKW1rb2zq4c7rhePsGh3IZxMUWJIMk2dhCOLm4eOUwACmQyaLZgWEwA6rhydBxBIWFMqmSwOEGI7V2wGlSceIVRxUul5alV6bXZ3o3NrTRTeUOq4mRMAMqqDKbEEUuxKwC+AhDyiiD0iBwQWtBgXOEQABmfglR7xR5AA).  In presets, you could name this Blade Flurry Jewels.

If you wanted you could create a few of these as Presets for faster recall.
