### ISSUE TITLE
total Crit chance for Spells doesn't count implicit on item.

### ISSUE THREAD

**Issue by BIGGekko** [poeapp/poeapp#128]
[total] #% increased Critical Strike Chance for Spells
dagger implicit should be added to total spell crit since it is "global" at least this is how poe.trade handle.

btw, I think"total Adds elemental damage to spell" is missing as searchable mod
so i don't need to add "lightning" "fire" "cold" mods on search

**Comment by poeapp** [comment]
Feel free to use [this search](https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4QALMaAEwGMB7aFAAgunlgDs8VoQAacFDhJUmWKgC2AFQCeAByKkAIvm68BEulTQkA2qE3aSoCHQhgsGAMQBSJpxqMwaFFSYBhOBFg0LTAMowsADWzO4UHDTMAGYMAQpYWDrEuhyIiXxpiQC6Aqbmlrb2kU4ubgDiWHTwfp7iPn6BcKEeEVF6WViZ6VjZAL558oogaIgS-CDQYFyKuiAAjADMAAz8nf39QA) in the meantime, until I can implement.

**Comment by poeapp** [comment]
`#% increased Critical Strike Chance for Spells` should now include `#% increased Global Critical Strike Chance` - this may take a while to correct

Also, `[total] Adds # Elemental Damage to Spells` was added a while ago.
