### ISSUE TITLE
Searching for alt arts shows multiple non alt art items

### ISSUE THREAD

**Issue by superouman** [poeapp/poeapp#130]
### Did you clear your browser cache before trying to reproduce?
- [X] Yes

### Did you disable all browser extensions before trying to reproduce?
- [X] Yes

### App Version
Current version is 2017-10-21T02:00:42.208Z

### Description
Searching for alt arts shows multiple non alt art items (Winterheart, Garukhan flight)
![poeapp_alt_art_bug](https://user-images.githubusercontent.com/5748216/31851059-9a21961e-b65e-11e7-8220-c25fb018307e.png)

### Expected outcome
Searching for alt arts should show only alt arts

### Actual outcome
Searching for alt arts shows multiple non alt art items

### Steps to reproduce
Open poeapp
select "Alternate Art" -> Yes
Launch search

### Browsers Affected

- [ x] Chrome
- [x ] Firefox
- [ x] Safari
- [x ] Edge
- [ x] IE 11
- [x ] iOS Safari
- [ x] Android Chrome
All browsers since it's server side.

**Comment by poeapp** [comment]
Seems they decided to flip the "naming convention" for Winterheart 🤔

#### Winterheart
http://web.poecdn.com/image/Art/2DItems/Amulets/WinterHeart.png
http://web.poecdn.com/image/Art/2DItems/Amulets/WinterHeartALT.png

versus

#### The Blood Thorn
http://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/TheBloodThorn.png
http://web.poecdn.com/image/Art/2DItems/Weapons/TwoHandWeapons/Staves/TheBloodThornALT.png

**Comment by poeapp** [comment]
This should be fixed moving forward.  Over the next few weeks, the index will see those items again and flag them as not alternate art (for now, those incorrect items will still show up in search results).  I also added better alternate art detection, so you may see some new items that weren't showing up before.

I also created a new issue https://github.com/poeapp/poeapp/issues/131 that will add detection for alt art flasks.

Thanks for the report 👍
