### ISSUE TITLE
Anti-Adblock still being displayed

### ISSUE THREAD

**Issue by yaaver2468** [poeapp/poeapp#133]
### Did you clear your browser cache before trying to reproduce?
- [✔️] Yes

### Did you disable all browser extensions before trying to reproduce?
- [✖] Yes

### App Version
2017-11-06T14:54:12.898Z

### Description
Message being displayed to disable adblocker regardless of having adblocker disabled.
Example: https://i.imgur.com/CrucN4j.png

### Expected outcome
Message to show when adblocker is actually enabled only.

### Steps to reproduce
Search for any item.

### Browsers Affected
- [✔️] Chrome
- [?] Firefox
- [?] Safari
- [?] Edge
- [?] IE 11
- [?] iOS Safari
- [?] Android Chrome

**Comment by poeapp** [comment]
This should be fixed in `2017-11-10T01:42:59.976Z`.  Please reopen if it's still an issue.

**Comment by yaaver2468** [comment]
Issue still occurring in version:
2017-11-13T04:00:40.068Z

![image](https://user-images.githubusercontent.com/28534561/32747807-f00d9dbc-c887-11e7-87fa-5543aa253e42.png)
