### ISSUE TITLE
Items that have been unlisted for a long time are appearing in searches

### ISSUE THREAD

**Issue by terkhen** [poeapp/poeapp#135]
### Did you clear your browser cache before trying to reproduce?
- [X] Yes

### Did you disable all browser extensions before trying to reproduce?
- [X] Yes

### App Version
Current version is 2017-12-11T14:45:37.283Z

### Description
Items in stash tabs that have been set to private weeks ago ago still appear in searches.

### Expected outcome
Items in private stash tabs should not appear in searches.

### Actual outcome
Items in stash tabs that have been set to private weeks ago ago still appear in searches.

### Steps to reproduce
1. Place an item in a public stash tab.
2. Set stash tab to private.
3. Wait for a long time. In my case, I set the stash tabs to private two weeks ago.
4. Go to poeapp.com and do a search setting "Seller" to your account name (and "Online" to off if you are currently not in game).
5. The items in the private stash tabs still appear in searches.

I am currently playing Abyss SSF and I set most of my stash tabs (except 40 chaos, and all exalted) to private about two weeks ago. You can search for my account name (terkhen) in Standard league to reproduce the issue; you should see a lot of cheap unique items listed for 1 Orb of Fusing.

Here is the direct link with the right league, account name and online set to off:
https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4Q0IwA7AEzGmpABoyALAewAcM0UsdoAggGMhbRJQgkQqaAGsWKSkxBtKWWJSKkUsCAuggAvkA

### Browsers Affected
- [X] Chrome
- [X] Firefox

I did not test with other browsers.

**Comment by terkhen** [comment]
I forgot to mention that I have also tried to log in to Standard again, log off, and then wait for a while to see if the items are removed from searches.

**Comment by poeapp** [comment]
@terkhen can you please test again when you have a moment?  Here are my steps:

1. Put items in a tab and set to public.
2. Change instances and wait 3-5 minutes.
3. Search for the account (with offline) to verify that items are available.
4. Set tab back to private and wait 3-5 minutes
5. Issue the search again and verify that items are no longer listed.

Please reopen if this is still an issue.

**Comment by terkhen** [comment]
I do not seem to have permissions for reopening issues.

I have followed your steps and that removed most of the items, but not all of them. That does not explain why all of those objects were still indexed, though.

If you retry the search now (https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4Q0IwA7AEzGmpABoyALAewAcM0UsdoAggGMhbRJQgkQqaAGsWKSkxBtKWWJSKkUsCAuggAvkA) you will see a few items listed for an Alchemy orb, with times from two weeks ago to one month ago. A few weeks ago I had all of my cheap items listed for an Alchemy orb, but then I decided to change all of them to an Orb of Fusing, so these items must come from before that.

Also, the search is showing an item that I already sold, the Heartbreaker. I suspect that following your steps again but also changing the price to Alchemy orb would remove the items from poeapp, except for the Heartbreaker.

**Comment by poeapp** [comment]
I found the following stashes listed under your account.  I have removed all of them currently.  Please confirm when you have a moment.

```
              "stashId" : "d047075807f41cfb281700bbf7592c12fdfaa7ff92ec307efea69726a859099b",
              "name" : "~b/o 1 alch",

              "stashId" : "26272d29be0900e275b86f28ac42b05d2483df601e3032e3f9a687835e1c23d6",
              "name" : "~b/o 1 alch",

              "stashId" : "ba1429f03c196a7e4d369f69656980f7445e0eb5bd18878b2dfa68c31035da91",
              "name" : "~b/o 1 alch",
```

**Comment by terkhen** [comment]
I can confirm that no stash tabs with that name are currently not present in my account. All of my trade stash tabs are set to fuses, chaos, or better. So yes, this solves the issue for me. I still wonder why those stash tabs were still linked, though.
