### ISSUE TITLE
API Endpoint to integrator with my new items price checker

### ISSUE THREAD

**Issue by C485** [poeapp/poeapp#139]
Hello,

Currently I working on app that shows an information about item with all information about a possibile price etc.
I faced an problem with making a hash of the request data on you API endpoint, i see that you are using "object-hash" with sha1 setup, but saddly i cannot generate such hash on C# side.

Could you privide a EndPoint without this hash checking thing?
It can be limited to X requests per minute because a amount of items that will be checked will be low, inventory+stashes.

Thanks for your work.

Best regards, Kamil.

**Comment by poeapp** [comment]
The APIs for poeapp are only meant to support poeapp.com and are not for consumption by the public; I do not have the server capacity in order to support this.

Apologies for this, but you will be banned if you consume the APIs outside of poeapp.
