### ISSUE TITLE
Mods Search Error

### ISSUE THREAD

**Issue by yaaver2468** [poeapp/poeapp#140]
### Did you clear your browser cache before trying to reproduce?
- [ ] Yes

### Did you disable all browser extensions before trying to reproduce?
- [ ] Yes

### App Version
2017-12-19T03:46:17.443Z

### Description
Searching for Remote Mine in the mods section doesn't return the result expected.

### Expected outcome
Something along the lines of "socketed gems are supported by level # remote mine"

### Actual outcome
![remote mine](https://user-images.githubusercontent.com/28534561/34183725-36755276-e4ea-11e7-9d11-6cb86acd261d.jpg)

### Browsers Affected

- [✔] Chrome
- [?] Firefox
- [?] Safari
- [?] Edge
- [?] IE 11
- [?] iOS Safari
- [?] Android Chrome

**Comment by poeapp** [comment]
This will be fixed in version `2018-01-01T00:17:21.754Z`

![remote mine](https://i.imgur.com/AJOURoc.png)

Please comment here if it's still an issue after upgrading.
