### ISSUE TITLE
Live searches no longer showing totals or removing items no longer for sale

### ISSUE THREAD

**Issue by Kha-Khan** [poeapp/poeapp#143]
### Did you clear your browser cache before trying to reproduce?
- [x] Yes

### Did you disable all browser extensions before trying to reproduce?
- [x] Yes

### App Version
2018-01-01T00:17:21.754Z

### Description
In the last few days, around Saturday Dec 30th, live search no longer shows totals in the search results. Also, it no longer removes searches you were too slow to get. Example below
Regular search works just as expected, it is only Live search with these issues.

### Expected outcome
1: Ring search: 
Blight Loop Sapphire Ring
ilvl: 75Level: 38
+30% to Cold Resistance
Adds 11 to 22 Fire Damage to Attacks
+12% to all Elemental Resistances
Adds 5 to 9 Physical Damage to Attacks
+68 to maximum Life
**Totals below**
+68 to maximum Life
+66% total to all Elemental Resistances

2:  Not removing searches for items that are sold.
If you leave your tab open for 20 minutes and say 10 things fit your search. if you click "Found 10. Click to show" it will show all 10, even if 8 of them are already sold.  Previously, it would only show ones that are still available. Maybe on GGG's end? unsure.

### Actual outcome
Blight Loop Sapphire Ring
ilvl: 75Level: 38
+30% to Cold Resistance
Adds 11 to 22 Fire Damage to Attacks
+12% to all Elemental Resistances
Adds 5 to 9 Physical Damage to Attacks
+68 to maximum Life
 
No totals! It does look neater but its really helpful to see the totals.

### Steps to reproduce
1.try this search https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC5x4BPNNEAGnCjiVU1lQFsAVcgByNIHEsAewBu6WiDZCAJtWIBtUFNklQEIRDBYMAagDEAAnUG2YAB6w2iNgYAysAGZ95AdgAMNAHaIsWALp03GgoiNJCunoApEYaWjEGWlgGAKI4bCiemkkASuiwaJqeAMbiCu5ePv506lkYUQawxdC4wdIGAIJQYEUA1gYAyrwo0iTyAJwVvn4AvtU8fOCeI9MzQA
(can be any search with totals or pseudo totals)
2. search live
3. no totals and if one gets sold before you click "Found X. Click to show" it will still be displayed.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge
- [x] IE 11
- [x] iOS Safari
- [x] Android Chrome

**Comment by poeapp** [comment]
What exactly is the problem?

**Comment by Kha-Khan** [comment]
sorry editing. apparently shift enter posts

**Comment by Kha-Khan** [comment]
Ok, written up now.

**Comment by poeapp** [comment]
Both of these should be fixed now.  Please test and comment here whether it is working or not.

**Comment by Kha-Khan** [comment]
Both are working ! thanks for making poeapp and updating it.
