### ISSUE TITLE
Search output gives faulty results sometimes

### ISSUE THREAD

**Issue by Dalekith** [poeapp/poeapp#145]
### Did you clear your browser cache before trying to reproduce?
- [x ] Yes

### Did you disable all browser extensions before trying to reproduce?
- [x ] Yes

### App Version
Current version is 2018-01-14T16:18:36.897Z

### Description
While searching for Elder Titanium Spirit Shield ilvl 80+ sometimes  Elder Thorium Spirit Shield ilvl 80+ sneaks in there.

### Steps to reproduce
https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC5x4BPNNEAGhFgDsAzAewwnIAcUAZRo0gBVYEMA1iIAtgAIAyp1hwIcgBawUWACa1wUOElSYNmlNBIgAmuh2QYCZOgywsANywkA2gA4ADDQaIWFgAugC+QA

### Video (optional)
https://www.dropbox.com/s/9rpfatnzsed8wz9/Screenshot%202018-01-14%2020.47.28.png?dl=0

### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by poeapp** [comment]
This should be fixed moving forward and seems to have only affected Magic items.  It may take a bit for the incorrectly identified items to resolve themselves, but in the meantime, you can type the typeline into the name field [like this](https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC5x4BPNNEAGhFgDsAzAewwhYGsUHYAvFABMMTRFiwA5MAFsipCLAhheiaQAI0AB1hwIGgBawUWQbXBQ4SVJmOCU0EiACa6M5BgJk6DLCwA3LBIAbQAOAAYaBjEsAF0AXyA).
