### ISSUE TITLE
"Total" Damage Mods

### ISSUE THREAD

**Issue by livejamie** [poeapp/poeapp#146]
poe.trade has mods for Total Elemental Spell Damage.

If an item has 10% Spell Damage and 22% Cold Damage then you can search for [Total] #% Increased Cold Spell Damage, in this example it would be listed at 32% Cold Damage.

It would be nice to have this in poeapp

**Comment by poeapp** [comment]
This should be fixed moving forward.

Added:
```
#% increased Fire Spell Damage
#% increased Cold Spell Damage
#% increased Lightning Spell Damage
```
