### ISSUE TITLE
"Total" Elemental Damage with Weapons

### ISSUE THREAD

**Issue by livejamie** [poeapp/poeapp#147]
Similar to what I suggest in #146 something that poe.trade doesn't have is total elemental damage with weapons.

It can be complicated to try to purchase items (especially jewels) that take into account mods that add elemental damage globally

So a jewel that has:
> Adds 6 to 11 Cold Damage to Spells
> Adds 17 to 22 Cold Damage to Spells while holding a Shield

Is _really_ 23 to 33 Cold Damage to spells while holding a Shield

> [Total] 27.5 Cold Damage to spells while holding a Shield

Search would be:

> [Total] # Cold Damage to Spells while holding a Shield

Would be nice for attacks as well.

Right now I'm playing a claw build and I just want the phat jewels that give me as much elemental damage with claws as possible.

This would be a great defining feature you could include.

Thanks!

**Comment by poeapp** [comment]
Closing this in favor of #157

**Comment by poeapp** [comment]
![screenshot](https://i.imgur.com/PwHHcQW.png)

It might take a bit for them to show up, but the mods are:

```
[total] Adds # Damage to Attacks
[total] Adds # Damage to Spells
```
