### ISSUE TITLE
Currency exchange lists corrupted maps without warning

### ISSUE THREAD

**Issue by Kuderion** [poeapp/poeapp#149]
Issue:
I am currently trying to sell a corrupted pit of the chimera map. 
Today I recieved two requests to buy it and in both cases the deal got cancelled when the other player saw that it was corrupted. Confused about it I searched for maps here and on poe.trade and found that poeapp (unlike poe.trade) lists my corrupted map in the currency search without any hint, so anyone wanting to buy a pit of the chimera who finds my listing gets (badly) surprised when he sees my corrupted map in the tradewindow.

Solution:
Please either remove corrupted maps from the currencysearch or add a warning to it, since unlike a uncorrupted map with a bad mod a corrupted map can't be simply scoured and alched, thus becomming worthless for some builds with a bad mod.

**Comment by poeapp** [comment]
Probably best to just note this in the UI rather than excluding all corrupted maps.

**Comment by poeapp** [comment]
![Mockup](https://i.imgur.com/P9KTxIN.png)

**Comment by poeapp** [comment]
Fixed as of version `2018-01-29T01:30:25.653Z`
