### ISSUE TITLE
Missing mods from abyss jewels

### ISSUE THREAD

**Issue by RDru** [poeapp/poeapp#153]
Those mods are missing from mod selection:
#% chance to gain Onslaught for 4 seconds on Kill
#% chance to gain Unholy Might for 4 seconds on Melee Kill
#% chance to gain Phasing for 4 seconds on Kill

**Comment by poeapp** [comment]
These mods will be showing up shortly:

![screenshot](https://i.imgur.com/4rISiRL.png)
