### ISSUE TITLE
"[pseudo] +#% total to all Elemental Resistances" don't count negative resistance mods

### ISSUE THREAD

**Issue by RDru** [poeapp/poeapp#154]
"[pseudo] +#% total to all Elemental Resistances" don't count negative resistance mods from Ventor's Gamble for example.

Also that mod could be ranamed to "[pseudo] +#% total Elemental Resistances" like on poe.trade. Right now it's confusing with "all Elemental Resistances" mod.

**Comment by poeapp** [comment]
This is fixed moving forward and unfortunately won't be retroactive.  As these items are reindexed, you will start seeing the change.

![Gambles](https://i.imgur.com/Lh3Wig3.png)
