### ISSUE TITLE
Allow searching for total combined damage on jewels

### ISSUE THREAD

**Issue by phrappuccino** [poeapp/poeapp#157]
For Abyssal Jewels it would be great to be able to search for a total combined damage value.
Distinctions between physical and elemental based on the weapon type would be very helpful.

[example] at least 70 combined elemental damage to wand attacks
[example] at least 15 combined physical damage to claw attacks

**Comment by poeapp** [comment]
@phrappuccino Could you please include the mods that affect those as well?  That way, I don't have to go digging through all of the jewel mods.

**Comment by phrappuccino** [comment]
Are the mods indexed somewhere so i can give you the indexnumber or do you just want me to write out all the names of the mods?

**Comment by poeapp** [comment]
Would be nice to see it like #147. This gives a clearer picture of which group of mods should affect the total mod that you would like added.

**Comment by phrappuccino** [comment]
Gonna shamelessly copy the skeleton from #147:

> Adds 6 to 11 Cold Damage to Attacks
> Adds 17 to 22 Cold Damage to Sword Attacks

Is really 23 to 33 Cold Damage to attacks while wieling a Sword

> [Total] 27.5 Cold Damage to attacks while wielding a Shield

Search would be:

> [Total] # Cold Damage to Sword Attacks

I will suggest the following groupings:
There are two reasonable ways to do this. Either you implement 3 subgroupings in the manner of:
total combined damage
total phyiscal damage and
total elemental damage

or only:
total combined damage and
total physical damage

The second option is definitely less work to implement while still maintaining an easy way to search for high combined damage jewels since the physical rolls are fairly low comapred to the elemental ones. The "cleaner" implement would be option mostly for the reason that newer players might not be able to distinct between the powerlevel of the average dmg rolls elemental vs physical (they will either want to search for phys or ele)

Example for Daggers:
total:

> Adds # to # lightning damage to dagger attacks
> Adds # to # lightning damage to attacks
> Adds # to # physical damage to dagger attacks
> Adds # to # physical damage to attacks

Search would be:

> [total] Combined Damage to Dagger Attacks

physical:

> Adds # to # physical damage to dagger attacks
> Adds # to # physical damage to attacks

Search would be:

> [total] Combined Physical Damage to Dagger Attacks

elemental:

> Adds # to # lightning damage to dagger attacks
> Adds # to # lightning damage to attacks

Search would be:

> [total] Combined Elemental Damage to Dagger Attacks

I would recommend only allowing to search for a total average damage. Not total combined min and max damage.

**Comment by phrappuccino** [comment]
If you want a listing like that for every weapon subtype and grouping let me know.

**Comment by poeapp** [comment]
Let's start with the ones that are most important to you.  Are you most interested in Wands/Claws?

**Comment by phrappuccino** [comment]
Claws:
total:

> Adds # to # lightning damage to claw attacks
> Adds # to # lightning damage to attacks
> Adds # to # physical damage to claw attacks
> Adds # to # physical damage to attacks

Search would be:

> [total] Combined Damage to Claw Attacks

physical:

> Adds # to # physical damage to claw attacks
> Adds # to # physical damage to attacks

Search would be:

> [total] Combined Physical Damage to Claw Attacks

elemental:

> Adds # to # lightning damage to claw attacks
> Adds # to # lightning damage to attacks

Search would be:

> [total] Combined Elemental Damage to Claw Attacks

**Comment by phrappuccino** [comment]
Swords:
total:

> Adds # to # lightning damage to Sword Attacks
> Adds # to # lightning damage to Attacks
> Adds # to # physical damage to Sword Attacks
> Adds # to # physical damage to Attacks

Search would be:

> [total] Combined Damage to Sword Attacks

physical:

> Adds # to # physical damage to Sword Attacks
> Adds # to # physical damage to Attacks

Search would be:

> [total] Combined Physical Damage to Sword Attacks

elemental:

> Adds # to # lightning damage to Sword Attacks
> Adds # to # lightning damage to Attacks

Search would be:

> [total] Combined Elemental Damage to Sword Attacks

**Comment by phrappuccino** [comment]
Axes:
total:

> Adds # to # lightning damage to Axe Attacks
> Adds # to # lightning damage to Attacks
> Adds # to # physical damage to Axe Attacks
> Adds # to # physical damage to Attacks

Search would be:

> [total] Combined Damage to Axe Attacks

physical:

> Adds # to # physical damage to Axe Attacks
> Adds # to # physical damage to Attacks

Search would be:

> [total] Combined Physical Damage to Axe Attacks

elemental:

> Adds # to # lightning damage to Axe Attacks
> Adds # to # lightning damage to Attacks

Search would be:

> [total] Combined Elemental Damage to Axe Attacks

**Comment by phrappuccino** [comment]
Maces:
total:

> Adds # to # lightning damage to Mace Attacks
> Adds # to # lightning damage to Attacks
> Adds # to # physical damage to Mace  Attacks
> Adds # to # physical damage to Attacks

Search would be:

> [total] Combined Damage to Mace  Attacks

physical:

> Adds # to # physical damage to Mace Attacks
> Adds # to # physical damage to Attacks

Search would be:

> [total] Combined Physical Damage to Mace Attacks

elemental:

> Adds # to # lightning damage to Mace Attacks
> Adds # to # lightning damage to Attacks

Search would be:

> [total] Combined Elemental Damage to Mace Attacks

**Comment by phrappuccino** [comment]
Staves:
total:

> Adds # to # lightning damage to Staff Attacks
> Adds # to # lightning damage to Attacks
> Adds # to # physical damage to Staff Attacks
> Adds # to # physical damage to Attacks

Search would be:

> [total] Combined Damage to Staff   Attacks

physical:

> Adds # to # physical damage to Staff Attacks
> Adds # to # physical damage to Attacks

Search would be:

> [total] Combined Physical Damage to Staff  Attacks

elemental:

> Adds # to # lightning damage to Staff Attacks
> Adds # to # lightning damage to Attacks

Search would be:

> [total] Combined Elemental Damage to Staff Attacks

**Comment by poeapp** [comment]
This is perfect 👍.  Thanks for including more detail.

**Comment by poeapp** [comment]
I'm looking through this and am starting to think that it makes more sense to add a mod such as `[total] Damage to Attacks` and include all of the mods above (bow, dagger, claw, etc) into that grouping.  That way a player could select an Item Type of Claw and select this mod.

Thoughts?

**Comment by poeapp** [comment]
![screenshot](https://i.imgur.com/PwHHcQW.png)

It might take a few hours for them to show up, but the new mods are:

```
[total] Adds # Damage to Attacks
[total] Adds # Damage to Spells
[total] Adds # Elemental Damage to Attacks
[total] Adds # Elemental Damage to Spells
[total] Adds # Physical Damage to Attacks
```
