### ISSUE TITLE
Incorrect prices shown during certain searches

### ISSUE THREAD

**Issue by Takkiz** [poeapp/poeapp#160]
### Did you clear your browser cache before trying to reproduce?
- [ ] Yes

### Did you disable all browser extensions before trying to reproduce?
- [ ] Yes

### Description
When searching "Craiceann's", results are  appearing that are priced drastically differently than sellers say they are priced.

**Comment by poeapp** [comment]
Need more info.  Can you point to specific examples of Sellers and compare to Path of Exile's official trading site please?

**Comment by poeapp** [comment]
Closing due to lack of response.
