### ISSUE TITLE
Change Chaos Orbs to chaos in whisper message

### ISSUE THREAD

**Issue by labo89** [poeapp/poeapp#161]
Hi, can the whisper message changed to be exactly like the poe.trade whisper message?

For example:
listed for 240 Chaos Orbs in bestiary to listed for 240 chaos in Bestiary

I am using MercuryTrade and with the current whisper message the currency won't show properly.

Edit: Change all the currency to how it is used on poe.trade

**Comment by poeapp** [comment]
You should request this feature at https://github.com/Exslims/MercuryTrade/issues

**Comment by labo89** [comment]
I will do that.

But the template should not be called poe.trade. It is not the same.

Sincerely
