### ISSUE TITLE
Presets gone

### ISSUE THREAD

**Issue by RDru** [poeapp/poeapp#162]
My presets are suddenly gone. Any way to recover them?

**Comment by poeapp** [comment]
What browser?

**Comment by RDru** [comment]
Firefox

**Comment by RDru** [comment]
I have found _pouch_presets without "db" in it. It's empty.

**Comment by poeapp** [comment]
If it's empty, then you're out of luck unfortunately.  Under the [settings](https://poeapp.com/#/settings) page there is a button that lets you copy the presets to your clipboard.  You can then upload them to a gist or pastebin for safe keeping.
