### ISSUE TITLE
PoeApp displays in white on chrome. Search doesn't work.

### ISSUE THREAD

**Issue by avalencia02** [poeapp/poeapp#163]
### Did you clear your browser cache before trying to reproduce?
- [YES]

### Did you disable all browser extensions before trying to reproduce?
- [YES]

### App Version
Chrome Current version is 2018-04-07T19:29:55.263Z

### Description
Main page has white background and difficult to read text. While items are searchable, no prices are displayed. Some errors appear in console.

### Expected outcome
Standard dark background. Usable search results. No errors in console.

### Image

https://imgur.com/Mrnv92h

### Browsers Affected

- [X] Chrome
- [?] Firefox
- [?] Safari
- [ ] Edge
- [~] IE 11 -> Similar white screen, no console errors. Browser crashed
- [?] iOS Safari
- [?] Android Chrome

**Comment by poeapp** [comment]
Can you please try doing a `Ctrl`+`F5`.

Also, are you in an incognito window?

**Comment by poeapp** [comment]
Closing due to lack of response.

Please comment here if this is still an issue.
