### ISSUE TITLE
Significant CPU & Memory Leak with detailed searches

### ISSUE THREAD

**Issue by Kha-Khan** [poeapp/poeapp#166]
### Did you clear your browser cache before trying to reproduce?
no, need the saved searches. 

### Are you using an incognito window?
no, need the saved searches

### Did you disable all browser extensions before trying to reproduce?
- [x] Yes

### App Version
2018-05-26T16:11:00.577Z

### Description
I have used PoeApp a long time. I have many very detailed searches.  I tried loading up poeapp today in Incursion and I got a crazy memory and CPU leak.  My CPU went up to 85% in chrome and memory went up to 5gb used until eventually the saved searches broke and I had to close poeapp.  I had used these searches as recently as the 2 week mayhem league in May 2018.  
By "searches broke" I mean that my searches now don't appear in Chrome, If I reboot my computer, my searches return but the cycle begins again with the memory leak.   After my searches get removed from site, my CPU and memory usage goes back down to normal.
I am fairly sure it has to do with my detailed searches so I posted them here (temporarily)
--removed pastebin link

### Expected outcome
CPU at 5-10%
Memory at 1-1.5gb

### Actual outcome
CPU at 80-85%
Memory at 5.5gb (then it breaks)

### Steps to reproduce
Hopefully you can reproduce with my pastebin link.  You can load any of the searches and it should reproduce the issue, even a fairly simple one like Opal Rings - Fire

### Browsers Affected

- [ x] Chrome
- [ x] Firefox

**Comment by poeapp** [comment]
Okay, tested it in Chrome `Version 66.0.3359.181 (Official Build) (64-bit)` with all of my extensions disabled.  Imported your presets, that worked fine.  Then I selected `Opal Ring - Fire` and hit search.  CPU went up temporarily (expected) and then came back down.

Seems you have your presets saved already, so could you please clear your cache, import the presets, and try again with extensions disabled?

![image](https://i.imgur.com/sW8kAwn.png)
![image](https://i.imgur.com/kjkNgWx.png)

**Comment by Kha-Khan** [comment]
Thanks for testing. I tried it again after clearing, this time on firefox and it was working then i tried Amulet -> early/mid and that started the CPU issue.
I was able to successfully do weapon flat phys missing 1 & 2 then opened a 3rd search with the amulets and then the problem resurfaced)

**Comment by poeapp** [comment]
Is it happening only in FF for you?  I can't seem to reproduce in Chrome still.  Would you mind taking a screen capture reproducing the steps and showing your task/tab manager please?

**Comment by Kha-Khan** [comment]
Sorry no video, I cleared my Chrome cache, then loaded this page, a poe wiki page and then loaded up the Phys missing searches 1 & 2, waited about 1 min for cpu to go down then took this screenshot.
[https://i.imgur.com/BLKeyR4.png](url)
Then I loaded the 3rd search, Amulet Early-Mid and I waited about 2min to see how high the usage would go, I stopped at what you see. PoeApp stopped functioning as I tried to click the Amulet search.
[https://i.imgur.com/PZZPDAD.png](url)

**Comment by poeapp** [comment]
Alright, I see that you have not disabled extensions in these examples.  Can you test again with your chrome extensions disabled?  For a better overview than windows task manager, you can hit `shift`+`esc` while Chrome is focused.

**Comment by Kha-Khan** [comment]
Tried just now with all extensions disabled. Same result.  If you still can't reproduce then it must be my problem, whatever it might be. Have enjoyed using the site, thank you for helping and providing the site and updates.   If I do ever figure it out i'll let you know.

side note,
normally run with adblock whitelisted for poeapp but early on in my testing, before post, I tried having adblock on.

**Comment by poeapp** [comment]
Can you please do me a favor and download [chrome canary](https://www.google.com/chrome/browser/canary.html).  Don't install any extensions and try to reproduce.  Let me know your findings please.

**Comment by Kha-Khan** [comment]
Chrome Canary produced the same issue, I downloaded it, went immediately to poeapp.com and imported the JSON. I did see a new type of Ad I haven't seen before.  Where the presets are, near the bottom of the page,  there was an ad you could minimize. 
Anyway, same usage issue once I open the 3rd poeapp instance.  A new problem, after I closed down all poeapp instances, I needed to reload this site as well, because it was stuck at 25% cpu usage, now at 0-3% .

**Comment by poeapp** [comment]
Okay, I think I have tracked it down.  Will try to get a patch for this out ASAP.  Might take up to a few days before I get something in place for this.

**Comment by poeapp** [comment]
Please update to version `2018-06-02T23:24:23.851Z` and let me know if you can reproduce.

**Comment by Kha-Khan** [comment]
It seems to have worked! Tried in Firefox and Chrome. thanks for working on my issue

**Comment by poeapp** [comment]
No worries.  Glad it's working now, and thank you for reporting.
