### ISSUE TITLE
Show Ranges on Hover

### ISSUE THREAD

**Issue by livejamie** [poeapp/poeapp#174]
One of the better features the official site is showing the ranges on affixes/suffixes on hover, would be nice to have

![image](https://user-images.githubusercontent.com/49513/42395464-e72b5844-8112-11e8-90bb-baf693133514.png)

**Comment by poeapp** [comment]
This will be available once GGG gives us access to the data.  They currently do not.

**Comment by livejamie** [comment]
Ah, good to know.  Sorry to clutter up your issues!

**Comment by poeapp** [comment]
Actually, it is available on hovering the S# or P#.  The tiers themselves are best guess, however.
