### ISSUE TITLE
Improving the UI

### ISSUE THREAD

**Issue by Sefriol** [poeapp/poeapp#47]
Hey!

I'm a big believer that mobile has decreased the usability of certain sites for desktop use when they increase padding and margins so that less information is shown in the screen at given time. 

When less information is shown, it increases the amount of scrolling required to operate the site and since trading sites are planned to improve the trading experience, faster they are to use, the better they are. Seeing all the form attributes before searching also reduces the amount of incorrect queries done to your database.

Paddings and margins are useful for touch devices since fingers are clunky pointers compared to a mouse. Since I don't have statistics about how many people use sites like this mobile, it's not clear how this should be addressed, but I would love if there were improvements done to the UI by removing unnecessary paddings and margins and reorganazing of some elements (Resistances in their own row, DPS in their own etc...). Maybe a desktop mode which can be enabled from the settings?

[I made a small mockup of this.](http://imgur.com/a/Ib7tp)

In addition I would user color/background images for different types of resistances and remove tautophony from the form (_chaos res, lightning res --> chaos, lightning and add a sub header called "Resistances". Same with the dps: dps, physical dps, elemental dps, chaos dps --> total, elemental, chaos with subheader dps_).

Additional improvements should be done to the results view. For example when listing weapons, the order of stats varies depending on which attributes the weapon has. Comparing stats between weapons is unintuitive. Indicating rarity with small ball seems unintuitive as well. Coloring the name itself seems like a better idea (shown in the mock up).

Maybe generate a totally new results view all together. I would say a table-like view would bring something new to the table (unintended pun ;) ). It would be much better when comparing hundreds of items (for example rings).

Of course, this is just my opinion and there are many things to like about in this site!

**Comment by poeapp** [comment]
Okay, lots has changed since this comment.

Resistances & Life have been added under the Defense section.

[Here is a link to a comment talking about the reasoning for the layout changes that were made.](https://www.reddit.com/r/pathofexile/comments/6qbycm/how_to_use_presets_on_poeappcom/dkwrdfy/)

[Here is a link to showcase how to use custom color/style overrides.](https://twitter.com/subtract/status/892829062619553792)

Thanks for the feedback. 👍
