### ISSUE TITLE
Customized whisper templates

### ISSUE THREAD

**Issue by just-a-bird** [poeapp/poeapp#51]
I'd like to use poe.trade's whisper format but use poeapp to generate them. I understand why you wouldn't want to copy their format, or use a more compact one or whatever. But I don't want to deviate from the norm and poeapp's current message doesn't get caught by popular trade apps (namely MercuryTrade), so it'd be nice to be able to customize it.

**Comment by poeapp** [comment]
Yeah, this is a feature that I have always planned to add but never got around to it.
