### ISSUE TITLE
Add Incomplete and inorder search words for mods

### ISSUE THREAD

**Issue by Svampen** [poeapp/poeapp#54]
Something I've always wanted to speed up searching is to be able to easier search through the different mods.
I would really like the possibility to just type in words (even incomplete) and in any order find the mod I'm looking for. 
For instance:
arm inc 
Would result in all mods with arm and inc matching any of the words in the mod text.

This would result in faster finding the current mods and remove the need to do "mum life" in order to quickly find "+ to maximum life" mod

**Comment by poeapp** [comment]
https://github.com/vaadin/vaadin-combo-box
https://gist.github.com/Saulis/48229751ba472e949b75eedc3d84de5b
https://github.com/vaadin/vaadin-combo-box/issues/106#issuecomment-284338695

**Comment by Svampen** [comment]
I'm not sure how vaadin-combo-box can be used to solve the requirement, especially the link to highlighting?

I tried the suggestion in jsbin, http://jsbin.com/lijumadewi/edit?html,output and you can't search on incomplete words or in order...

**Comment by poeapp** [comment]
Sorry for the confusion.  Those links are for my reference :)

**Comment by poeapp** [comment]
Adding this as well: http://elasticlunr.com/

**Comment by poeapp** [comment]
Alright, just released an experiment for this with the `Name` field only.  If performance isn't an issue, I will try to apply it to mods.  https://twitter.com/subtract/status/930896409955516416

**Comment by poeapp** [comment]
Preview : https://imgur.com/a/YClTy

**Comment by poeapp** [comment]
Enjoy : https://twitter.com/subtract/status/931297353973219328

**Comment by Svampen** [comment]
Excellent work!
