### ISSUE TITLE
"Please reload the page."

### ISSUE THREAD

**Issue by MrTastix** [poeapp/poeapp#56]
Been getting this message when trying to search for items for the past week now. Doesn't seem to be specific to any particular group, either, as I get the problem when searching for maps, currency, rares, uniques, etc.

[Image example.](https://i.imgur.com/T659vSP.png)

Clicking the "reload the page" link, manually refreshing, or even trying to reload and search again doesn't fix the issue.

Only seems to be an issue on Google Chrome, with or without extensions. Firefox does not experience the same problems, nor Microsoft Edge.

**Comment by poeapp** [comment]
When you reload the page, are you getting the DDOS protection check landing for a few seconds?

**Comment by MrTastix** [comment]
Oh! No, I'm not, actually.

Get it on Firefox more than I do on Chrome.

**Comment by poeapp** [comment]
Let me know if a ctrl+f5 on the app fixes the issue for you please.

**Comment by MrTastix** [comment]
Yeah, that fixed it. Thanks!

**Comment by poeapp** [comment]
Good to hear.  I will make that error message more descriptive when I get a chance.
