### ISSUE TITLE
"(leaguestone) Can only be used in Areas with Monster Level # or below" missing from modifiers list

### ISSUE THREAD

**Issue by just-a-bird** [poeapp/poeapp#61]
Used for filtering leaguestones. Present on `poe.trade`.

**Comment by poeapp** [comment]
Please use ilvl - it's either 67 or 68, can't remember.

**Comment by just-a-bird** [comment]
Makes sense, will do. May want to implement it eventually, though, as it's not immediately obvious.

**Comment by poeapp** [comment]
Yeah, I think it makes more sense to just expose all possible properties in the mods dropdown in some form or another.  That way it solves this and future use cases.
