### ISSUE TITLE
"no other mods" checkbox

### ISSUE THREAD

**Issue by Drusekx** [poeapp/poeapp#65]
The idea is to search for items with only selected mods and nothing else. For example I want to look for 3-mod jewels from like 10 mods - so I put those 10 mods, select "count min 3 max 3" - normally I would get the list of jewels with those 3 mods without or with another mod, but I want to select "no other mods" and filter out everything that isn't on my mod list.

**Comment by poeapp** [comment]
Just adding notes: Might be better to expose min/max field for `explicit` - this way, someone could just select their mods, then put in a max of `n` mods.

**Comment by poeapp** [comment]
[Possibly something like this](https://twitter.com/subtract/status/846746325127454720)

**Comment by poeapp** [comment]
This should be live in 4-5 hours, please reopen if this doesn't not address your needs.
