### ISSUE TITLE
UI element for hiding the search form

### ISSUE THREAD

**Issue by just-a-bird** [poeapp/poeapp#73]
Am I just missing it, or is the only way to hide it via the hotkeys?

**Comment by poeapp** [comment]
Can currently only hide via the hotkeys.  However, once hidden there is a button to show it.

**Comment by poeapp** [comment]
Closing this as it is no longer relevant as of version `2018-01-13T23:52:11.858Z`.  You can now toggle the search/results with `(ctrl or alt) + s` or start a new search with `(ctrl or alt) + r`.  Use `ctrl` on a mac and `alt` on windows.
