### ISSUE TITLE
Ability to remove presets from the dropdown

### ISSUE THREAD

**Issue by just-a-bird** [poeapp/poeapp#83]
If this functionality already exists, I apologise. I couldn't find it.

**Comment by poeapp** [comment]
No worries :) I started working on this, but it's not ready for production yet.  Related to https://github.com/poeapp/poeapp/issues/19

**Comment by poeapp** [comment]
This is in place now under settings http://imgur.com/a/M0LZ4

**Comment by just-a-bird** [comment]
Awesome, nice work!
