### ISSUE TITLE
max in "Count" group doesn't work

### ISSUE THREAD

**Issue by Drusekx** [poeapp/poeapp#86]
### Description
max in "Count" group doesn't work

### Expected outcome
max in "Count" group should filter out all items that have more mods than the max

### Actual outcome
it shows items that have more mods from the group than max

### Steps to reproduce
1. Open this page: poeapp.com/#N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4Qc8wBjATxABpwo4lVNZUBbAFWoAcjSAIQD2wiGnqMYCZOgzQwcCLVILoRBh2EATCcQDaoLbpKheaFIm3CMAagDEAAi5iwWRxGGOOYAB6wORA5HABlYADMBfRAARgAGOMkQAF0AXwZlfhJwADttEHSjHT1QFF9eLFhKdjsnT28-AKDQiKicxCwsOnbO5IYyiqqahw8vAGUYFBy8CAALEn0erqW0jL4BEEphRByISQVpqNjJGJTUtKA
2. Despite select max count of mods to 1 it shows 2. (Normally this search should not find items.)

### Browsers Affected
all?

**Comment by poeapp** [comment]
Fixed in version `0e1013e48de41f29ee5df125045860ef67a6699c`.  Please clear your cache, check the version under the settings page, and confirm.  If it's still not working as expected, please reopen.
