### ISSUE TITLE
Search page ad never loads

### ISSUE THREAD

**Issue by sherlockmatt** [poeapp/poeapp#93]
### Description
When loading a search page, the ad at the top doesn't load, and the loading icon in the tab never stops. This suggests a request (or multiple) never completes. Adblock is off (as always on your site).

Let me know if you need any more info :)

### Expected outcome
![image](https://cloud.githubusercontent.com/assets/5717750/26025998/18cd692c-37eb-11e7-8260-9260bef8674e.png)
![image](https://cloud.githubusercontent.com/assets/5717750/26025911/984d95ac-37e9-11e7-831e-97f1156e793d.png)
![image](https://cloud.githubusercontent.com/assets/5717750/26026008/4bcb669e-37eb-11e7-8a75-d9f79e02987a.png)

### Actual outcome
![image](https://cloud.githubusercontent.com/assets/5717750/26025971/6b118390-37ea-11e7-9f65-9edb5c32bf5e.png)
![image](https://cloud.githubusercontent.com/assets/5717750/26025920/abf761fa-37e9-11e7-9584-d410ee34957c.png)
![image](https://cloud.githubusercontent.com/assets/5717750/26025975/7ba37272-37ea-11e7-9d0a-454af56a61b6.png)

### Steps to reproduce
I used [this page](https://poeapp.com/#N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4Qc8wBjATxABoRYA7AMwHsMI2BrFJ2AF4oAJhhaIsWAHJgAtkVIBBPExTQ2wgARS20CAAtNASVkAHNbDBZNAZQhgWLeiDT62pjPrBoACnEoKIACa6M6u7hiUXmxoJCAAbCAAvkA) to test with, not sure if it's all pages but I would imagine so.

### Browsers Affected
- [yes] Chrome
- [no] Firefox
- [?] Safari
- [no] Edge
- [?] IE 11
- [?] iOS Safari
- [no] Android Chrome

**Comment by poeapp** [comment]
Matthew,

Do you have a whole network adblocker using a hosts file or dnsmasq?  In a cmd prompt/term, can you ping doubleclick.net and screenshot the results please?

Thanks

**Comment by poeapp** [comment]
Could you confirm what version you're using please?  You can see this at the bottom of the Settings page.

**Comment by sherlockmatt** [comment]
Current version is e1c504277a6dfe893d0d4d524786440820eac46b

No global adblocker or anything that I'm aware of, it worked on all other browsers except Chrome.

![image](https://cloud.githubusercontent.com/assets/5717750/26026449/644556aa-37f3-11e7-9074-c136d51dc2c1.png)

**Comment by poeapp** [comment]
Do me a favor and open your network panel, get it as big as you possibly can, and do a Ctrl+F5 on the page.  It would also be helpful if you clicked into one of two that were failing and took screenshots of the Headers tab (Response+Request).

**Comment by sherlockmatt** [comment]
4k screenshot :D
![image](https://cloud.githubusercontent.com/assets/5717750/26026635/d7a0782a-37f6-11e7-80d9-b95bcd0bd390.png)

![image](https://cloud.githubusercontent.com/assets/5717750/26026653/417fe7bc-37f7-11e7-8732-05b757cacf23.png)

![image](https://cloud.githubusercontent.com/assets/5717750/26026654/45c4809e-37f7-11e7-9d14-8e293c1c050b.png)

The others that are failing show very similar things.

**Comment by poeapp** [comment]
Thanks for this.  I'll dig into it and will let you know what I find.  I'll try to figure out a way to reproduce this on my end.

**Comment by sherlockmatt** [comment]
No problem. Just let me know if I can help. I'll keep testing it out every now and then to see if it's a temporary thing.

**Comment by poeapp** [comment]
Okay, I bumped the version to `def7a3644dd0b0e71e085265bda6a41ed3881298` and cleared the CDN cache.  If you Ctrl+F5, you might get lucky and be able to pull the latest.

**Comment by sherlockmatt** [comment]
I've got that version now, problem still exists :(

**Comment by poeapp** [comment]
Do you have another computer in the house that you can test with?  Just use chrome with all the extensions disabled, if possible please.

**Comment by sherlockmatt** [comment]
Tested on my Android phone's Chrome (on the same wifi), no problem. No other computers available unfortunately.

**Comment by sherlockmatt** [comment]
Hmmm, weird. While AdBlock is disabled for your entire domain name, and claims it is off, it is actually blocking the ad. Disabling the entire extension in Chrome allows it to load properly. Enabling it again breaks the ad. Maybe this is a bug with adblock then instead, or _possibly_ it thinks the ad is so dangerous that it wants to block it anyway?

I'll test some more later this evening and update you.

**Comment by poeapp** [comment]
Interesting find.  Is your chrome up-to-date?  Also, you should try downloading and using ublock origin, disable the adblock extension, and whitelist using ublock origin.  Let me know your findings.

**Comment by sherlockmatt** [comment]
Chrome is up to date. Switched from AdBlock to uBlock as you suggested, that's fixed it :) uBlock seems better actually, might just stick to this from now on!

Not sure whether to close this or not, since I'm now certain this is an AdBlock bug. I'll leave it up to you, I don't mind.

**Comment by poeapp** [comment]
Okay, that's good to know.  It seems like AdBlock is doing something wrong when you whitelist.  It's possible that it could be caching something behind the scenes.  Whatever it is, I assume that they will fix it in a future version.  uBlock is a little nicer and has lower memory usage overall.

Thanks for pointing out the bug and helping debug :)  Hope you enjoy the tool.  Feel free to reopen if you run into problems in the future.
