### ISSUE TITLE
Many-item search won't start, "Something went wrong"

### ISSUE THREAD

**Issue by justsuggestslol** [poeapp/poeapp#98]
### Description
A large search for jewels matching an AND and a COUNT:2 search will not initiate.

### Expected outcome
The search searches, and finds jewels with some of the selected mods + %max life.

### Actual outcome
Search does not initiate, instead pop-up "Something went wrong" error box.

### Steps to reproduce
1. Open this page: https://poeapp.com/search/N4IghgLhBOCWBGBXCBTAzgOgDYrAc0RRAC4Qc8wBjATxABpwo4lVNZUBbAFWoAcjSAKRQB3FFnogOAewAmaEgG1QM+SVAoAHryyxK7DAGIApAAJYAO0rRcaFLNMBBKFQDWpgMr97pkewAWpgDCWGAiCsSKFohYWHTRsQC6DFo6egYm5lY2YHYOAAr+1Gh6YFimACJgHPgovgHBoeFKCXGtySCpuvoQRmaW1rY+zhBunt4OfhCBVXh4KNARUTFtKx1d6b2ZAzl5poXFpeVVNfP105X484stK-FrKdrdGf3ZQw4jY14oPlOBjpp0LdYvcko80j0+llBrkfAcSpQypdTnU-k5AUtWqCsOsnpsoTt3k4XJR3N9fg0ALJUIGRLHtcHPLavGF7eFHZG1c6BamUWnLEEMzp4yHbN6wj4kskTbmeETSaBqOl3IUbUUs3ZwooIpEnLlojzyxWYlUPYUQl7QzWS0ak8Y-SYNADyFjqAAkwBZZD5KeIfqYAOq4XjSCwmwVmtWWwkS-bajl6s5ol3uz3ehy+nB1INgENh4GrMHmpkYADUmQg0mCcAgHI8MFgrjqlJitbSCwL2NxFt65bMler7DrDabphbWDbugWvn8sBwlUQSIDsHEskseE7qpFBj7pgHQRrw7go-Hk5X0FlKdMHq9Pr92eDofDhZxjPxYtZwyl9vsm8j2+ZK0iU+O002CXIIB-WQlBAAAWegtx7AlxTZeNEWOapaj-Iso0AmM9kzf1EwEAUX27EsP2tTl5mwnEAF8GAgPgBBAShpEQCwIEkaBPRoyIQAAJgQtYGJUOQIg0ADkM-Bwak0WAOEQDhTAAGVgAAzEj6RExjmJIcAvRAOjEjooA
2. Search

### Browsers Affected

- [ ] Chrome
- [ x ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by poeapp** [comment]
I tried to reproduce in FF 54.0.1 and wasn't successful.  At the bottom of the settings page in poeapp, what version do you see?  Latest is currently `815663342e8abbd4ec99ec9c234c03452dce01d2`.  Could you please try clearing your browser cache and testing again?

**Comment by poeapp** [comment]
Please reopen if this is still an issue.
